//! Virtual network device for smoltcp
//!
//! This module provides a virtual network device that bridges smoltcp's TCP/IP
//! stack with in-memory packet queues. Packets are exchanged through these queues
//! rather than real network interfaces.
//!
//! # Architecture
//!
//! ```text
//! ┌─────────────────┐     ┌─────────────────────┐     ┌──────────────────┐
//! │ smoltcp stack   │ <-> │   VirtualDevice     │ <-> │ WireGuard tunnel │
//! │ (TCP/IP)        │     │   (packet queues)   │     │ (encryption)     │
//! └─────────────────┘     └─────────────────────┘     └──────────────────┘
//! ```
//!
//! # Usage
//!
//! ```ignore
//! use rust_router::netbridge::smoltcp::{VirtualDevice, WG_MTU};
//!
//! // Create device
//! let mut device = VirtualDevice::new(WG_MTU);
//!
//! // Feed packets from WireGuard (RX direction: WG -> smoltcp)
//! device.push_rx(decrypted_packet);
//!
//! // Drain packets to send through WireGuard (TX direction: smoltcp -> WG)
//! for packet in device.drain_tx() {
//!     wg_tunnel.send(&packet).await?;
//! }
//! ```
//!
//! # Thread Safety
//!
//! `VirtualDevice` is NOT thread-safe. It should be owned by a single task
//! (typically `SmoltcpShard`) and accessed only from that task.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};

use smoltcp::phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken};
use smoltcp::time::Instant as SmoltcpInstant;
use tracing::trace;

use super::{DEVICE_RX_BUFFER_CAPACITY, DEVICE_TX_BUFFER_CAPACITY, WG_MTU};

// =============================================================================
// VirtualDevice Statistics
// =============================================================================

/// Statistics for the virtual device
#[derive(Debug, Default)]
pub struct VirtualDeviceStats {
    /// Packets received (RX: WG -> smoltcp)
    pub rx_packets: AtomicU64,
    /// Packets transmitted (TX: smoltcp -> WG)
    pub tx_packets: AtomicU64,
    /// Bytes received
    pub rx_bytes: AtomicU64,
    /// Bytes transmitted
    pub tx_bytes: AtomicU64,
    /// Packets dropped due to full RX buffer
    pub rx_dropped: AtomicU64,
    /// Packets dropped due to full TX buffer
    pub tx_dropped: AtomicU64,
}

impl VirtualDeviceStats {
    /// Create new zeroed statistics
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Get a snapshot of statistics
    #[must_use]
    pub fn snapshot(&self) -> VirtualDeviceStatsSnapshot {
        VirtualDeviceStatsSnapshot {
            rx_packets: self.rx_packets.load(Ordering::Relaxed),
            tx_packets: self.tx_packets.load(Ordering::Relaxed),
            rx_bytes: self.rx_bytes.load(Ordering::Relaxed),
            tx_bytes: self.tx_bytes.load(Ordering::Relaxed),
            rx_dropped: self.rx_dropped.load(Ordering::Relaxed),
            tx_dropped: self.tx_dropped.load(Ordering::Relaxed),
        }
    }
}

impl Clone for VirtualDeviceStats {
    fn clone(&self) -> Self {
        Self {
            rx_packets: AtomicU64::new(self.rx_packets.load(Ordering::Relaxed)),
            tx_packets: AtomicU64::new(self.tx_packets.load(Ordering::Relaxed)),
            rx_bytes: AtomicU64::new(self.rx_bytes.load(Ordering::Relaxed)),
            tx_bytes: AtomicU64::new(self.tx_bytes.load(Ordering::Relaxed)),
            rx_dropped: AtomicU64::new(self.rx_dropped.load(Ordering::Relaxed)),
            tx_dropped: AtomicU64::new(self.tx_dropped.load(Ordering::Relaxed)),
        }
    }
}

/// Snapshot of virtual device statistics (for reporting)
#[derive(Debug, Clone, Default)]
pub struct VirtualDeviceStatsSnapshot {
    /// Packets received (RX: WG -> smoltcp)
    pub rx_packets: u64,
    /// Packets transmitted (TX: smoltcp -> WG)
    pub tx_packets: u64,
    /// Bytes received
    pub rx_bytes: u64,
    /// Bytes transmitted
    pub tx_bytes: u64,
    /// Packets dropped due to full RX buffer
    pub rx_dropped: u64,
    /// Packets dropped due to full TX buffer
    pub tx_dropped: u64,
}

// =============================================================================
// VirtualDevice
// =============================================================================

/// Virtual network device for smoltcp with in-memory packet queues
///
/// This device operates at the IP layer (`Medium::Ip`) since WireGuard
/// handles packets at Layer 3 (no Ethernet framing).
///
/// # Packet Flow
///
/// - **RX direction** (WireGuard -> smoltcp): Decrypted IP packets from WireGuard
///   are pushed to `rx_buffer`. smoltcp reads them via `receive()`.
/// - **TX direction** (smoltcp -> WireGuard): IP packets generated by smoltcp
///   are written to `tx_buffer` via `transmit()`. They are drained and encrypted
///   by WireGuard.
pub struct VirtualDevice {
    /// Maximum transmission unit
    mtu: usize,
    /// Packets to transmit (smoltcp -> WG)
    tx_buffer: Vec<Vec<u8>>,
    /// Packets received (WG -> smoltcp) — VecDeque for FIFO ordering
    /// CRITICAL: Must be FIFO so smoltcp processes TCP segments in-order,
    /// avoiding unnecessary reassembly overhead and duplicate ACKs.
    rx_buffer: VecDeque<Vec<u8>>,
    /// Statistics
    stats: VirtualDeviceStats,
}

impl VirtualDevice {
    /// Create a new virtual device with the given MTU
    ///
    /// # Arguments
    ///
    /// * `mtu` - Maximum transmission unit (typically 1420 for WireGuard)
    #[must_use]
    pub fn new(mtu: usize) -> Self {
        Self {
            mtu,
            tx_buffer: Vec::with_capacity(DEVICE_TX_BUFFER_CAPACITY),
            rx_buffer: VecDeque::with_capacity(DEVICE_RX_BUFFER_CAPACITY),
            stats: VirtualDeviceStats::new(),
        }
    }

    /// Create a new virtual device with default WireGuard MTU
    #[must_use]
    pub fn with_default_mtu() -> Self {
        Self::new(WG_MTU)
    }

    /// Get the configured MTU
    #[must_use]
    pub fn mtu(&self) -> usize {
        self.mtu
    }

    /// Push a received packet to the RX buffer (WG -> smoltcp)
    ///
    /// This is called when a decrypted IP packet is received from WireGuard.
    /// The packet will be processed by smoltcp on the next `poll()` call.
    ///
    /// # Arguments
    ///
    /// * `packet` - The decrypted IP packet from WireGuard
    ///
    /// # Returns
    ///
    /// `true` if the packet was queued, `false` if the buffer is full
    pub fn push_rx(&mut self, packet: Vec<u8>) -> bool {
        if self.rx_buffer.len() >= DEVICE_RX_BUFFER_CAPACITY {
            trace!(
                len = packet.len(),
                capacity = DEVICE_RX_BUFFER_CAPACITY,
                "VirtualDevice RX buffer full, dropping packet"
            );
            self.stats.rx_dropped.fetch_add(1, Ordering::Relaxed);
            return false;
        }

        let len = packet.len();
        self.rx_buffer.push_back(packet);
        self.stats.rx_packets.fetch_add(1, Ordering::Relaxed);
        self.stats.rx_bytes.fetch_add(len as u64, Ordering::Relaxed);

        trace!(len, queue_len = self.rx_buffer.len(), "Packet pushed to RX");
        true
    }

    /// Drain all TX packets (smoltcp -> WG)
    ///
    /// Returns all packets that smoltcp has generated for transmission.
    /// These should be encrypted and sent through WireGuard.
    #[must_use]
    pub fn drain_tx(&mut self) -> Vec<Vec<u8>> {
        std::mem::take(&mut self.tx_buffer)
    }

    /// Drain TX packets into the provided vector
    ///
    /// More efficient than `drain_tx()` when you want to reuse a buffer.
    pub fn drain_tx_into(&mut self, out: &mut Vec<Vec<u8>>) {
        out.append(&mut self.tx_buffer);
    }

    /// Check if there are RX packets waiting for smoltcp
    #[must_use]
    pub fn has_rx(&self) -> bool {
        !self.rx_buffer.is_empty()
    }

    /// Check if there are TX packets waiting for WireGuard
    #[must_use]
    pub fn has_tx(&self) -> bool {
        !self.tx_buffer.is_empty()
    }

    /// Check if the RX buffer can accept more packets
    #[must_use]
    pub fn can_push_rx(&self) -> bool {
        self.rx_buffer.len() < DEVICE_RX_BUFFER_CAPACITY
    }

    /// Check if the TX buffer can accept more packets
    #[must_use]
    pub fn can_push_tx(&self) -> bool {
        self.tx_buffer.len() < DEVICE_TX_BUFFER_CAPACITY
    }

    /// Get the number of pending RX packets
    #[must_use]
    pub fn rx_queue_len(&self) -> usize {
        self.rx_buffer.len()
    }

    /// Get the number of pending TX packets
    #[must_use]
    pub fn tx_queue_len(&self) -> usize {
        self.tx_buffer.len()
    }

    /// Clear both buffers
    pub fn clear(&mut self) {
        self.rx_buffer.clear();
        self.tx_buffer.clear();
    }

    /// Get statistics reference
    #[must_use]
    pub fn stats(&self) -> &VirtualDeviceStats {
        &self.stats
    }

    /// Get a snapshot of statistics
    #[must_use]
    pub fn stats_snapshot(&self) -> VirtualDeviceStatsSnapshot {
        self.stats.snapshot()
    }
}

impl std::fmt::Debug for VirtualDevice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VirtualDevice")
            .field("mtu", &self.mtu)
            .field("rx_queue_len", &self.rx_buffer.len())
            .field("tx_queue_len", &self.tx_buffer.len())
            .finish()
    }
}

// =============================================================================
// smoltcp Device trait implementation
// =============================================================================

/// RX token for reading a packet from the device
///
/// Consumed when smoltcp wants to process a received packet.
pub struct VirtualRxToken {
    /// The packet data
    packet: Vec<u8>,
}

impl RxToken for VirtualRxToken {
    fn consume<R, F>(self, f: F) -> R
    where
        F: FnOnce(&[u8]) -> R,
    {
        trace!(len = self.packet.len(), "VirtualRxToken consumed");
        f(&self.packet)
    }
}

/// TX token for sending a packet through the device
///
/// Consumed when smoltcp wants to send a packet.
pub struct VirtualTxToken<'a> {
    /// Reference to the TX buffer
    tx_buffer: &'a mut Vec<Vec<u8>>,
    /// Reference to statistics
    stats: &'a VirtualDeviceStats,
}

impl<'a> TxToken for VirtualTxToken<'a> {
    fn consume<R, F>(self, len: usize, f: F) -> R
    where
        F: FnOnce(&mut [u8]) -> R,
    {
        // Allocate buffer for the packet
        let mut buffer = vec![0u8; len];
        let result = f(&mut buffer);

        // Check if we can push
        if self.tx_buffer.len() < DEVICE_TX_BUFFER_CAPACITY {
            self.stats.tx_packets.fetch_add(1, Ordering::Relaxed);
            self.stats.tx_bytes.fetch_add(len as u64, Ordering::Relaxed);
            self.tx_buffer.push(buffer);
            trace!(len, queue_len = self.tx_buffer.len(), "Packet pushed to TX");
        } else {
            self.stats.tx_dropped.fetch_add(1, Ordering::Relaxed);
            trace!(len, "TX buffer full, dropping packet");
        }

        result
    }
}

impl Device for VirtualDevice {
    type RxToken<'a> = VirtualRxToken where Self: 'a;
    type TxToken<'a> = VirtualTxToken<'a> where Self: 'a;

    fn receive(
        &mut self,
        _timestamp: SmoltcpInstant,
    ) -> Option<(Self::RxToken<'_>, Self::TxToken<'_>)> {
        // Pop a packet from the RX buffer (FIFO for correct TCP segment ordering)
        if let Some(packet) = self.rx_buffer.pop_front() {
            trace!(
                len = packet.len(),
                remaining = self.rx_buffer.len(),
                "Device receive"
            );
            Some((
                VirtualRxToken { packet },
                VirtualTxToken {
                    tx_buffer: &mut self.tx_buffer,
                    stats: &self.stats,
                },
            ))
        } else {
            None
        }
    }

    fn transmit(&mut self, _timestamp: SmoltcpInstant) -> Option<Self::TxToken<'_>> {
        // Always allow transmission if buffer has space
        if self.tx_buffer.len() < DEVICE_TX_BUFFER_CAPACITY {
            Some(VirtualTxToken {
                tx_buffer: &mut self.tx_buffer,
                stats: &self.stats,
            })
        } else {
            None
        }
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();

        // WireGuard operates at IP layer (no Ethernet framing)
        caps.medium = Medium::Ip;
        caps.max_transmission_unit = self.mtu;

        // Tx = compute checksum on transmit, skip verification on receive.
        // TX checksums are REQUIRED: after WG decapsulation, the remote peer's kernel
        // verifies inner packet checksums. Poly1305 MAC only protects the WG layer.
        // RX verification can be skipped since WG integrity covers incoming packets.
        caps.checksum.ipv4 = smoltcp::phy::Checksum::Tx;
        caps.checksum.tcp = smoltcp::phy::Checksum::Tx;
        caps.checksum.udp = smoltcp::phy::Checksum::Tx;
        caps.checksum.icmpv4 = smoltcp::phy::Checksum::Tx;

        caps
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_device_new() {
        let device = VirtualDevice::new(1420);
        assert_eq!(device.mtu(), 1420);
        assert!(!device.has_rx());
        assert!(!device.has_tx());
        assert!(device.can_push_rx());
        assert!(device.can_push_tx());
    }

    #[test]
    fn test_device_with_default_mtu() {
        let device = VirtualDevice::with_default_mtu();
        assert_eq!(device.mtu(), WG_MTU);
    }

    #[test]
    fn test_push_rx() {
        let mut device = VirtualDevice::new(1420);

        assert!(device.push_rx(vec![1, 2, 3, 4]));
        assert!(device.has_rx());
        assert_eq!(device.rx_queue_len(), 1);

        let stats = device.stats_snapshot();
        assert_eq!(stats.rx_packets, 1);
        assert_eq!(stats.rx_bytes, 4);
    }

    #[test]
    fn test_drain_tx() {
        let mut device = VirtualDevice::new(1420);

        // Simulate smoltcp writing packets via transmit token
        device.tx_buffer.push(vec![1, 2, 3]);
        device.tx_buffer.push(vec![4, 5, 6]);

        assert!(device.has_tx());
        assert_eq!(device.tx_queue_len(), 2);

        let packets = device.drain_tx();
        assert_eq!(packets.len(), 2);
        assert_eq!(packets[0], vec![1, 2, 3]);
        assert_eq!(packets[1], vec![4, 5, 6]);

        assert!(!device.has_tx());
    }

    #[test]
    fn test_drain_tx_into() {
        let mut device = VirtualDevice::new(1420);
        device.tx_buffer.push(vec![1, 2, 3]);

        let mut out = Vec::new();
        device.drain_tx_into(&mut out);

        assert_eq!(out.len(), 1);
        assert_eq!(out[0], vec![1, 2, 3]);
        assert!(!device.has_tx());
    }

    #[test]
    fn test_rx_buffer_overflow() {
        let mut device = VirtualDevice::new(1420);

        // Fill the RX buffer
        for i in 0..DEVICE_RX_BUFFER_CAPACITY {
            assert!(device.push_rx(vec![i as u8]), "Failed at index {}", i);
        }

        assert!(!device.can_push_rx());

        // Next push should fail
        assert!(!device.push_rx(vec![255]));

        let stats = device.stats_snapshot();
        assert_eq!(stats.rx_dropped, 1);
    }

    #[test]
    fn test_clear() {
        let mut device = VirtualDevice::new(1420);

        device.push_rx(vec![1, 2, 3]);
        device.tx_buffer.push(vec![4, 5, 6]);

        device.clear();

        assert!(!device.has_rx());
        assert!(!device.has_tx());
    }

    #[test]
    fn test_device_capabilities() {
        let device = VirtualDevice::new(1420);
        let caps = device.capabilities();

        assert_eq!(caps.medium, Medium::Ip);
        assert_eq!(caps.max_transmission_unit, 1420);
    }

    #[test]
    fn test_device_receive() {
        let mut device = VirtualDevice::new(1420);
        let timestamp = SmoltcpInstant::from_millis(0);

        // No packets, receive should return None
        assert!(device.receive(timestamp).is_none());

        // Add a packet
        device.push_rx(vec![1, 2, 3, 4]);

        // Now receive should return tokens
        let (rx_token, _tx_token) = device.receive(timestamp).expect("Should have packet");

        // Consume the RX token
        let result = rx_token.consume(|buf| {
            assert_eq!(buf, &[1, 2, 3, 4]);
            buf.len()
        });
        assert_eq!(result, 4);
    }

    #[test]
    fn test_device_transmit() {
        let mut device = VirtualDevice::new(1420);
        let timestamp = SmoltcpInstant::from_millis(0);

        // Transmit should return a token
        let tx_token = device.transmit(timestamp).expect("Should get TX token");

        // Consume the TX token to send a packet
        tx_token.consume(4, |buf| {
            buf.copy_from_slice(&[5, 6, 7, 8]);
        });

        // Packet should be in the TX buffer
        let packets = device.drain_tx();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0], vec![5, 6, 7, 8]);
    }

    #[test]
    fn test_stats_snapshot() {
        let mut device = VirtualDevice::new(1420);

        device.push_rx(vec![1, 2, 3, 4, 5]);
        device.push_rx(vec![6, 7, 8]);

        let snapshot = device.stats_snapshot();
        assert_eq!(snapshot.rx_packets, 2);
        assert_eq!(snapshot.rx_bytes, 8);
        assert_eq!(snapshot.tx_packets, 0);
    }

    #[test]
    fn test_device_debug() {
        let device = VirtualDevice::new(1420);
        let debug_str = format!("{:?}", device);
        assert!(debug_str.contains("VirtualDevice"));
        assert!(debug_str.contains("1420"));
    }
}
