# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Modified for broader grpcio version compatibility.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import v2ray_stats_pb2 as v2ray__stats__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__

# Relaxed version check - only warn instead of raising error
# This allows the code to work with older grpcio versions in Docker
try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION}, '
        f'but this code was generated with grpcio-tools {GRPC_GENERATED_VERSION}. '
        f'Some features may not work correctly. Consider upgrading grpcio.',
        RuntimeWarning
    )


class StatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStats = channel.unary_unary(
                '/xray.app.stats.command.StatsService/GetStats',
                request_serializer=v2ray__stats__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=v2ray__stats__pb2.GetStatsResponse.FromString)
        self.GetStatsOnline = channel.unary_unary(
                '/xray.app.stats.command.StatsService/GetStatsOnline',
                request_serializer=v2ray__stats__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=v2ray__stats__pb2.GetStatsResponse.FromString)
        self.QueryStats = channel.unary_unary(
                '/xray.app.stats.command.StatsService/QueryStats',
                request_serializer=v2ray__stats__pb2.QueryStatsRequest.SerializeToString,
                response_deserializer=v2ray__stats__pb2.QueryStatsResponse.FromString)
        self.GetSysStats = channel.unary_unary(
                '/xray.app.stats.command.StatsService/GetSysStats',
                request_serializer=v2ray__stats__pb2.SysStatsRequest.SerializeToString,
                response_deserializer=v2ray__stats__pb2.SysStatsResponse.FromString)
        self.GetStatsOnlineIpList = channel.unary_unary(
                '/xray.app.stats.command.StatsService/GetStatsOnlineIpList',
                request_serializer=v2ray__stats__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=v2ray__stats__pb2.GetStatsOnlineIpListResponse.FromString)


class StatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSysStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsOnlineIpList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=v2ray__stats__pb2.GetStatsRequest.FromString,
                    response_serializer=v2ray__stats__pb2.GetStatsResponse.SerializeToString,
            ),
            'GetStatsOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsOnline,
                    request_deserializer=v2ray__stats__pb2.GetStatsRequest.FromString,
                    response_serializer=v2ray__stats__pb2.GetStatsResponse.SerializeToString,
            ),
            'QueryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStats,
                    request_deserializer=v2ray__stats__pb2.QueryStatsRequest.FromString,
                    response_serializer=v2ray__stats__pb2.QueryStatsResponse.SerializeToString,
            ),
            'GetSysStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSysStats,
                    request_deserializer=v2ray__stats__pb2.SysStatsRequest.FromString,
                    response_serializer=v2ray__stats__pb2.SysStatsResponse.SerializeToString,
            ),
            'GetStatsOnlineIpList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsOnlineIpList,
                    request_deserializer=v2ray__stats__pb2.GetStatsRequest.FromString,
                    response_serializer=v2ray__stats__pb2.GetStatsOnlineIpListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xray.app.stats.command.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xray.app.stats.command.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.stats.command.StatsService/GetStats',
            v2ray__stats__pb2.GetStatsRequest.SerializeToString,
            v2ray__stats__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetStatsOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.stats.command.StatsService/GetStatsOnline',
            v2ray__stats__pb2.GetStatsRequest.SerializeToString,
            v2ray__stats__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def QueryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.stats.command.StatsService/QueryStats',
            v2ray__stats__pb2.QueryStatsRequest.SerializeToString,
            v2ray__stats__pb2.QueryStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetSysStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.stats.command.StatsService/GetSysStats',
            v2ray__stats__pb2.SysStatsRequest.SerializeToString,
            v2ray__stats__pb2.SysStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def GetStatsOnlineIpList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray.app.stats.command.StatsService/GetStatsOnlineIpList',
            v2ray__stats__pb2.GetStatsRequest.SerializeToString,
            v2ray__stats__pb2.GetStatsOnlineIpListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
