# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v2ray_stats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v2ray_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11v2ray_stats.proto\x12\x1cv2ray.core.app.stats.command\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"D\n\x10GetStatsResponse\x12\x30\n\x04stat\x18\x01 \x01(\x0b\x32\".v2ray.core.app.stats.command.Stat\"Y\n\x11QueryStatsRequest\x12\x13\n\x07pattern\x18\x01 \x01(\tB\x02\x18\x01\x12\r\n\x05reset\x18\x02 \x01(\x08\x12\x10\n\x08patterns\x18\x03 \x03(\t\x12\x0e\n\x06regexp\x18\x04 \x01(\x08\"F\n\x12QueryStatsResponse\x12\x30\n\x04stat\x18\x01 \x03(\x0b\x32\".v2ray.core.app.stats.command.Stat\"\x11\n\x0fSysStatsRequest\"\xc2\x01\n\x10SysStatsResponse\x12\x14\n\x0cNumGoroutine\x18\x01 \x01(\r\x12\r\n\x05NumGC\x18\x02 \x01(\r\x12\r\n\x05\x41lloc\x18\x03 \x01(\x04\x12\x12\n\nTotalAlloc\x18\x04 \x01(\x04\x12\x0b\n\x03Sys\x18\x05 \x01(\x04\x12\x0f\n\x07Mallocs\x18\x06 \x01(\x04\x12\r\n\x05\x46rees\x18\x07 \x01(\x04\x12\x13\n\x0bLiveObjects\x18\x08 \x01(\x04\x12\x14\n\x0cPauseTotalNs\x18\t \x01(\x04\x12\x0e\n\x06Uptime\x18\n \x01(\r2\xd8\x02\n\x0cStatsService\x12i\n\x08GetStats\x12-.v2ray.core.app.stats.command.GetStatsRequest\x1a..v2ray.core.app.stats.command.GetStatsResponse\x12o\n\nQueryStats\x12/.v2ray.core.app.stats.command.QueryStatsRequest\x1a\x30.v2ray.core.app.stats.command.QueryStatsResponse\x12l\n\x0bGetSysStats\x12-.v2ray.core.app.stats.command.SysStatsRequest\x1a..v2ray.core.app.stats.command.SysStatsResponseB4Z2github.com/sagernet/sing-box/experimental/v2rayapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v2ray_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/sagernet/sing-box/experimental/v2rayapi'
  _globals['_QUERYSTATSREQUEST'].fields_by_name['pattern']._loaded_options = None
  _globals['_QUERYSTATSREQUEST'].fields_by_name['pattern']._serialized_options = b'\030\001'
  _globals['_GETSTATSREQUEST']._serialized_start=51
  _globals['_GETSTATSREQUEST']._serialized_end=97
  _globals['_STAT']._serialized_start=99
  _globals['_STAT']._serialized_end=134
  _globals['_GETSTATSRESPONSE']._serialized_start=136
  _globals['_GETSTATSRESPONSE']._serialized_end=204
  _globals['_QUERYSTATSREQUEST']._serialized_start=206
  _globals['_QUERYSTATSREQUEST']._serialized_end=295
  _globals['_QUERYSTATSRESPONSE']._serialized_start=297
  _globals['_QUERYSTATSRESPONSE']._serialized_end=367
  _globals['_SYSSTATSREQUEST']._serialized_start=369
  _globals['_SYSSTATSREQUEST']._serialized_end=386
  _globals['_SYSSTATSRESPONSE']._serialized_start=389
  _globals['_SYSSTATSRESPONSE']._serialized_end=583
  _globals['_STATSSERVICE']._serialized_start=586
  _globals['_STATSSERVICE']._serialized_end=930
# @@protoc_insertion_point(module_scope)
